project_id = "uszopnkydweixqgyfynj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://imobiia-frontend-v2.vercel.app"]
jwt_expiry = 3600
enable_refresh_token_rotation = true

[functions.invite-corretor]
verify_jwt = true
