/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedOportunidadesRouteImport } from './routes/_authenticated/oportunidades'
import { Route as AuthenticatedImoveisRouteImport } from './routes/_authenticated/imoveis'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOportunidadesIndexRouteImport } from './routes/_authenticated/oportunidades.index'
import { Route as AuthenticatedImoveisIndexRouteImport } from './routes/_authenticated/imoveis.index'
import { Route as AuthenticatedOportunidadesNovoRouteImport } from './routes/_authenticated/oportunidades.novo'
import { Route as AuthenticatedImoveisNovoRouteImport } from './routes/_authenticated/imoveis.novo'
import { Route as AuthenticatedOportunidadesIdEditarRouteImport } from './routes/_authenticated/oportunidades.$id.editar'
import { Route as AuthenticatedImoveisIdEditarRouteImport } from './routes/_authenticated/imoveis.$id.editar'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOportunidadesRoute =
  AuthenticatedOportunidadesRouteImport.update({
    id: '/oportunidades',
    path: '/oportunidades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImoveisRoute = AuthenticatedImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOportunidadesIndexRoute =
  AuthenticatedOportunidadesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOportunidadesRoute,
  } as any)
const AuthenticatedImoveisIndexRoute =
  AuthenticatedImoveisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedImoveisRoute,
  } as any)
const AuthenticatedOportunidadesNovoRoute =
  AuthenticatedOportunidadesNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedOportunidadesRoute,
  } as any)
const AuthenticatedImoveisNovoRoute =
  AuthenticatedImoveisNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedImoveisRoute,
  } as any)
const AuthenticatedOportunidadesIdEditarRoute =
  AuthenticatedOportunidadesIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedOportunidadesRoute,
  } as any)
const AuthenticatedImoveisIdEditarRoute =
  AuthenticatedImoveisIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedImoveisRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/imoveis': typeof AuthenticatedImoveisRouteWithChildren
  '/oportunidades': typeof AuthenticatedOportunidadesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/imoveis/novo': typeof AuthenticatedImoveisNovoRoute
  '/oportunidades/novo': typeof AuthenticatedOportunidadesNovoRoute
  '/imoveis/': typeof AuthenticatedImoveisIndexRoute
  '/oportunidades/': typeof AuthenticatedOportunidadesIndexRoute
  '/imoveis/$id/editar': typeof AuthenticatedImoveisIdEditarRoute
  '/oportunidades/$id/editar': typeof AuthenticatedOportunidadesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/imoveis/novo': typeof AuthenticatedImoveisNovoRoute
  '/oportunidades/novo': typeof AuthenticatedOportunidadesNovoRoute
  '/imoveis': typeof AuthenticatedImoveisIndexRoute
  '/oportunidades': typeof AuthenticatedOportunidadesIndexRoute
  '/imoveis/$id/editar': typeof AuthenticatedImoveisIdEditarRoute
  '/oportunidades/$id/editar': typeof AuthenticatedOportunidadesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/imoveis': typeof AuthenticatedImoveisRouteWithChildren
  '/_authenticated/oportunidades': typeof AuthenticatedOportunidadesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/imoveis/novo': typeof AuthenticatedImoveisNovoRoute
  '/_authenticated/oportunidades/novo': typeof AuthenticatedOportunidadesNovoRoute
  '/_authenticated/imoveis/': typeof AuthenticatedImoveisIndexRoute
  '/_authenticated/oportunidades/': typeof AuthenticatedOportunidadesIndexRoute
  '/_authenticated/imoveis/$id/editar': typeof AuthenticatedImoveisIdEditarRoute
  '/_authenticated/oportunidades/$id/editar': typeof AuthenticatedOportunidadesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/imoveis'
    | '/oportunidades'
    | '/auth/login'
    | '/auth/signup'
    | '/imoveis/novo'
    | '/oportunidades/novo'
    | '/imoveis/'
    | '/oportunidades/'
    | '/imoveis/$id/editar'
    | '/oportunidades/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/imoveis/novo'
    | '/oportunidades/novo'
    | '/imoveis'
    | '/oportunidades'
    | '/imoveis/$id/editar'
    | '/oportunidades/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/imoveis'
    | '/_authenticated/oportunidades'
    | '/auth/login'
    | '/auth/signup'
    | '/_authenticated/imoveis/novo'
    | '/_authenticated/oportunidades/novo'
    | '/_authenticated/imoveis/'
    | '/_authenticated/oportunidades/'
    | '/_authenticated/imoveis/$id/editar'
    | '/_authenticated/oportunidades/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/oportunidades': {
      id: '/_authenticated/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AuthenticatedOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imoveis': {
      id: '/_authenticated/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof AuthenticatedImoveisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/oportunidades/': {
      id: '/_authenticated/oportunidades/'
      path: '/'
      fullPath: '/oportunidades/'
      preLoaderRoute: typeof AuthenticatedOportunidadesIndexRouteImport
      parentRoute: typeof AuthenticatedOportunidadesRoute
    }
    '/_authenticated/imoveis/': {
      id: '/_authenticated/imoveis/'
      path: '/'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof AuthenticatedImoveisIndexRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
    '/_authenticated/oportunidades/novo': {
      id: '/_authenticated/oportunidades/novo'
      path: '/novo'
      fullPath: '/oportunidades/novo'
      preLoaderRoute: typeof AuthenticatedOportunidadesNovoRouteImport
      parentRoute: typeof AuthenticatedOportunidadesRoute
    }
    '/_authenticated/imoveis/novo': {
      id: '/_authenticated/imoveis/novo'
      path: '/novo'
      fullPath: '/imoveis/novo'
      preLoaderRoute: typeof AuthenticatedImoveisNovoRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
    '/_authenticated/oportunidades/$id/editar': {
      id: '/_authenticated/oportunidades/$id/editar'
      path: '/$id/editar'
      fullPath: '/oportunidades/$id/editar'
      preLoaderRoute: typeof AuthenticatedOportunidadesIdEditarRouteImport
      parentRoute: typeof AuthenticatedOportunidadesRoute
    }
    '/_authenticated/imoveis/$id/editar': {
      id: '/_authenticated/imoveis/$id/editar'
      path: '/$id/editar'
      fullPath: '/imoveis/$id/editar'
      preLoaderRoute: typeof AuthenticatedImoveisIdEditarRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
  }
}

interface AuthenticatedImoveisRouteChildren {
  AuthenticatedImoveisNovoRoute: typeof AuthenticatedImoveisNovoRoute
  AuthenticatedImoveisIndexRoute: typeof AuthenticatedImoveisIndexRoute
  AuthenticatedImoveisIdEditarRoute: typeof AuthenticatedImoveisIdEditarRoute
}

const AuthenticatedImoveisRouteChildren: AuthenticatedImoveisRouteChildren = {
  AuthenticatedImoveisNovoRoute: AuthenticatedImoveisNovoRoute,
  AuthenticatedImoveisIndexRoute: AuthenticatedImoveisIndexRoute,
  AuthenticatedImoveisIdEditarRoute: AuthenticatedImoveisIdEditarRoute,
}

const AuthenticatedImoveisRouteWithChildren =
  AuthenticatedImoveisRoute._addFileChildren(AuthenticatedImoveisRouteChildren)

interface AuthenticatedOportunidadesRouteChildren {
  AuthenticatedOportunidadesNovoRoute: typeof AuthenticatedOportunidadesNovoRoute
  AuthenticatedOportunidadesIndexRoute: typeof AuthenticatedOportunidadesIndexRoute
  AuthenticatedOportunidadesIdEditarRoute: typeof AuthenticatedOportunidadesIdEditarRoute
}

const AuthenticatedOportunidadesRouteChildren: AuthenticatedOportunidadesRouteChildren =
  {
    AuthenticatedOportunidadesNovoRoute: AuthenticatedOportunidadesNovoRoute,
    AuthenticatedOportunidadesIndexRoute: AuthenticatedOportunidadesIndexRoute,
    AuthenticatedOportunidadesIdEditarRoute:
      AuthenticatedOportunidadesIdEditarRoute,
  }

const AuthenticatedOportunidadesRouteWithChildren =
  AuthenticatedOportunidadesRoute._addFileChildren(
    AuthenticatedOportunidadesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImoveisRoute: typeof AuthenticatedImoveisRouteWithChildren
  AuthenticatedOportunidadesRoute: typeof AuthenticatedOportunidadesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImoveisRoute: AuthenticatedImoveisRouteWithChildren,
  AuthenticatedOportunidadesRoute: AuthenticatedOportunidadesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
